# This file is covered by the LICENSE file in the root of this project.

nbr_classes: 15
learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
  10: 1     # "car"
  11: 2     # "bicycle"
  13: 1     # "bus"
  15: 3     # "motorcycle"
  16: 1     # "on-rails" mapped to "other-vehicle" ---------------------mapped
  18: 1     # "truck"
  20: 1     # "other-vehicle"
  30: 4     # "person"
  31: 5     # "bicyclist"
  32: 5     # "motorcyclist"
  40: 6     # "road"
  44: 0    # "parking" ---ignore
  48: 7    # "sidewalk"
  49: 8   # "other-ground"
  50: 9    # "building"
  51: 0    # "fence" ---ignore
  52: 0     # "other-structure" ---ignore
  60: 6     # "lane-marking" mapped to "road"
  70: 10    # "vegetation"
  71: 11    # "trunk"
  72: 0    # "terrain" ---ignore
  80: 12    # "pole"
  81: 13    # "traffic-sign"
  99: 14     # "other-object"
  252: 1    # "moving-car" to "car" ------------------------------------mapped
  253: 5    # "moving-bicyclist" to "bicyclist" ------------------------mapped
  254: 4    # "moving-person" to "person" ------------------------------mapped
  255: 5    # "moving-motorcyclist" to "motorcyclist" ------------------mapped
  256: 1    # "moving-on-rails" mapped to "other-vehicle" --------------mapped
  257: 1    # "moving-bus" mapped to "bus" -------------------mapped
  258: 1    # "moving-truck" to "truck" --------------------------------mapped
  259: 1    # "moving-other"-vehicle to "other-vehicle" ----------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 10     # "car"
  2: 11     # "bicycle"
  3: 15     # "motorcycle"
  4: 30     # "person"
  5: 31     # "bicyclist" + "motorcyclist"
  6: 40    # "road" + "lane marking"
  7: 48    # "sidewalk"
  8: 49    # "other-ground"
  9: 50    # "building"
  10: 70    # "vegetation"
  11: 71    # "trunk"
  12: 80    # "pole"
  13: 81    # "traffic-sign"
  14: 99    # "other-object"
learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     
  2: False     
  3: False     
  4: False    
  5: False     
  6: False     
  7: False    
  8: False    
  9: False   
  10: False  
  11: False   
  12: False   
  13: False  
  14: False  


#UNIFIED
# nbr_classes: 11
# learning_map:
#   0 : 0     # "unlabeled"
#   1 : 0     # "outlier" mapped to "unlabeled" --------------------------mapped
#   10: 1     # "car"
#   11: 2     # "bicycle"
#   13: 1     # "bus"
#   15: 3     # "motorcycle"
#   16: 1     # "on-rails" mapped to "other-vehicle" ---------------------mapped
#   18: 1     # "truck"
#   20: 1     # "other-vehicle"
#   30: 4     # "person"
#   31: 0     # "bicyclist" mapped to "unlabeled" --------------------------mapped
#   32: 0     # "motorcyclist" mapped to "unlabeled" --------------------------mapped
#   40: 5     # "road"
#   44: 0    # "parking" ---ignore
#   48: 6    # "sidewalk"
#   49: 7   # "other-ground"
#   50: 8    # "building"
#   51: 0    # "fence" ---ignore
#   52: 0     # "other-structure" ---ignore
#   60: 6     # "lane-marking" mapped to "road" --------------------------mapped
#   70: 9    # "vegetation"
#   71: 9    # "trunk" mapped to "vegetation" --------------------------mapped
#   72: 0    # "terrain" ---ignore
#   80: 10    # "pole" mapped to "other obejct" --------------------------mapped
#   81: 10    # "traffic-sign" mapped to "other object" --------------------------mapped
#   99: 10     # "other-object"
#   252: 1    # "moving-car" to "car" ------------------------------------mapped
#   253: 0    # "moving-bicyclist" to "unlabeled" ------------------------mapped
#   254: 4    # "moving-person" to "person" ------------------------------mapped
#   255: 0    # "moving-motorcyclist" to "unlabeled" ------------------mapped
#   256: 1    # "moving-on-rails" mapped to "car" --------------mapped
#   257: 1    # "moving-bus" mapped to "car" -------------------mapped
#   258: 1    # "moving-truck" to "car" --------------------------------mapped
#   259: 1    # "moving-other"-vehicle to "car" ----------------mapped
# learning_map_inv: # inverse of previous map
#   0: 0      # "unlabeled", and others ignored
#   1: 10     # "car"
#   2: 11     # "bicycle"
#   3: 15     # "motorcycle"
#   4: 30     # "person"
#   5: 40    # "road"
#   6: 48    # "sidewalk"
#   7: 49    # "other-ground"
#   8: 50    # "building"
#   9: 70    # "vegetation"
#   10: 99    # "other-object"
# learning_ignore: # Ignore classes
#   0: True      # "unlabeled", and others ignored
#   1: False     
#   2: False     
#   3: False     
#   4: False    
#   5: False     
#   6: False     
#   7: False    
#   8: False    
#   9: False   
#   10: False    






grid_dims: [256, 32, 256]  # (W, H, D)
labels:
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
content: # as a ratio with the total number of points
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  11: 0.00016609538710764618
  13: 2.7879693665067774e-05
  15: 0.00039838616015114444
  16: 0.0
  18: 0.0020633612104619787
  20: 0.0016218197275284021
  30: 0.00017698551338515307
  31: 1.1065903904919655e-08
  32: 5.532951952459828e-09
  40: 0.1987493871255525
  44: 0.014717169549888214
  48: 0.14392298360372
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  52: 0.002395131480328884
  60: 4.7084144280367186e-05
  70: 0.26681502148037506
  71: 0.006035012012626033
  72: 0.07814222006271769
  80: 0.002855498193863172
  81: 0.0006155958086189918
  99: 0.009923127583046915
  252: 0.001789309418528068
  253: 0.00012709999297008662
  254: 0.00016059776092534436
  255: 3.745553104802113e-05
  256: 0.0
  257: 0.00011351574470342043
  258: 0.00010157861367183268
  259: 4.3840131989471124e-05
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent